import type { Course, Testimonial, PricingPlan, FAQ, BlogPost } from "@/types";

export const MOCK_COURSES: Course[] = [
  {
    id: "1",
    title: "Full Stack Web Development Bootcamp",
    description: "Master React, Node.js, MongoDB, and deploy production apps.",
    instructor: "Alex Johnson",
    category: "Web Development",
    level: "Intermediate",
    duration: "48 hours",
    students: 12450,
    rating: 4.9,
    reviews: 2341,
    price: 79,
    originalPrice: 199,
    thumbnail: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=250&fit=crop",
    tags: ["React", "Node.js", "MongoDB", "TypeScript"],
    progress: 65,
  },
  {
    id: "2",
    title: "Machine Learning with Python",
    description: "Build real ML models from regression to neural networks.",
    instructor: "Dr. Sarah Chen",
    category: "AI & ML",
    level: "Advanced",
    duration: "56 hours",
    students: 8920,
    rating: 4.8,
    reviews: 1876,
    price: 89,
    originalPrice: 249,
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=250&fit=crop",
    tags: ["Python", "TensorFlow", "Scikit-learn", "Deep Learning"],
    progress: 30,
  },
  {
    id: "3",
    title: "Cloud Architecture on AWS",
    description: "Design, deploy, and manage scalable cloud infrastructure.",
    instructor: "Michael Torres",
    category: "Cloud Computing",
    level: "Intermediate",
    duration: "40 hours",
    students: 6780,
    rating: 4.7,
    reviews: 1234,
    price: 69,
    originalPrice: 189,
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop",
    tags: ["AWS", "Docker", "Kubernetes", "DevOps"],
  },
  {
    id: "4",
    title: "Cybersecurity Fundamentals",
    description: "Learn ethical hacking, network security, and threat analysis.",
    instructor: "Emma Wilson",
    category: "Cybersecurity",
    level: "Beginner",
    duration: "32 hours",
    students: 9450,
    rating: 4.8,
    reviews: 1987,
    price: 59,
    originalPrice: 149,
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop",
    tags: ["Security", "Networking", "Ethical Hacking", "OWASP"],
  },
  {
    id: "5",
    title: "Data Science & Analytics",
    description: "Transform raw data into actionable business insights.",
    instructor: "Dr. Raj Patel",
    category: "Data Science",
    level: "Intermediate",
    duration: "44 hours",
    students: 7650,
    rating: 4.9,
    reviews: 1654,
    price: 75,
    originalPrice: 199,
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    tags: ["Python", "SQL", "Tableau", "Statistics"],
  },
  {
    id: "6",
    title: "Mobile App Development with React Native",
    description: "Build cross-platform iOS and Android apps with one codebase.",
    instructor: "Lisa Park",
    category: "Mobile Development",
    level: "Intermediate",
    duration: "38 hours",
    students: 5430,
    rating: 4.7,
    reviews: 987,
    price: 65,
    originalPrice: 169,
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=250&fit=crop",
    tags: ["React Native", "iOS", "Android", "Expo"],
    isFree: false,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Priya Sharma",
    role: "Frontend Developer",
    company: "TechCorp India",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
    content: "VedTechno transformed my career. The AI coding assistant helped me understand complex concepts faster than any bootcamp I've attended. Got hired within 3 months!",
    rating: 5,
  },
  {
    id: "2",
    name: "Marcus Chen",
    role: "Data Scientist",
    company: "DataWave Analytics",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    content: "The project-based learning approach is exceptional. I built 5 real-world projects that became the backbone of my portfolio. The AI guidance was invaluable.",
    rating: 5,
  },
  {
    id: "3",
    name: "Sarah Mitchell",
    role: "Cloud Engineer",
    company: "CloudNine Solutions",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    content: "I earned my AWS certification through VedTechno in just 2 months. The practice environments are top-notch and the community support is incredible.",
    rating: 5,
  },
  {
    id: "4",
    name: "Arjun Nair",
    role: "Startup Founder",
    company: "NeuralStack",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    content: "The Innovation Hub gave my startup the technical foundation it needed. Mentorship access and the founder community helped us launch our product 40% faster.",
    rating: 5,
  },
  {
    id: "5",
    name: "Emily Rodriguez",
    role: "HR & L&D Manager",
    company: "Global Enterprises",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face",
    content: "We enrolled 150 employees on the enterprise plan. The team analytics helped us identify skill gaps and improve our tech capabilities by 60% in one quarter.",
    rating: 5,
  },
  {
    id: "6",
    name: "David Kim",
    role: "Full Stack Developer",
    company: "Freelance",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    content: "The interactive coding lab with multi-language support is phenomenal. I can switch between Python, JavaScript, and Go seamlessly. Best learning investment I've made.",
    rating: 5,
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    description: "Perfect for beginners exploring technology learning.",
    price: { monthly: 0, annual: 0 },
    features: [
      "5 free courses access",
      "Basic coding challenges",
      "Community forum access",
      "1 project lab",
      "Email support",
      "Basic skill assessments",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    description: "For serious learners and professionals.",
    price: { monthly: 29, annual: 19 },
    features: [
      "Unlimited course access",
      "AI coding assistant",
      "Advanced coding labs",
      "10 project labs",
      "Digital certificates",
      "Career roadmaps",
      "Mock interviews",
      "Priority support",
      "Resume builder",
      "Job board access",
    ],
    highlighted: true,
    badge: "Most Popular",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "For teams and organizations scaling their tech talent.",
    price: { monthly: 99, annual: 79 },
    features: [
      "Everything in Pro",
      "Team management",
      "Custom learning paths",
      "Advanced analytics",
      "Employee certifications",
      "Corporate training programs",
      "Dedicated account manager",
      "SSO & SAML support",
      "API access",
      "Custom branding",
    ],
  },
];

export const FAQS: FAQ[] = [
  {
    question: "What makes VedTechno different from other online learning platforms?",
    answer: "VedTechno combines AI-powered learning tools, interactive coding labs, real-world project building, and career development in one ecosystem. Our AI coding assistant provides personalized guidance, while our project-based approach ensures you build a portfolio that stands out to employers.",
  },
  {
    question: "How does the AI Coding Assistant work?",
    answer: "Our AI Coding Assistant analyzes your code in real-time, provides intelligent suggestions, detects bugs, offers refactoring recommendations, and generates documentation. It learns from your coding patterns to provide increasingly personalized guidance as you progress.",
  },
  {
    question: "Are the certifications industry-recognized?",
    answer: "Yes! VedTechno certifications are recognized by hundreds of tech companies worldwide. Our assessments are proctored, skill-validated, and include digital badges verifiable on LinkedIn and professional platforms. Many of our employer partners specifically seek VedTechno certified candidates.",
  },
  {
    question: "Can I access courses on mobile devices?",
    answer: "Absolutely! VedTechno is fully responsive and optimized for mobile learning. Our mobile app (iOS & Android) lets you continue lessons, participate in discussions, and even code directly from your phone with our mobile-optimized code editor.",
  },
  {
    question: "What programming languages does the coding lab support?",
    answer: "Our Interactive Coding Lab supports 20+ programming languages including Python, JavaScript, TypeScript, Java, C++, Go, Rust, PHP, Ruby, Swift, Kotlin, and more. Multi-language projects with cross-language support are also available for full-stack development.",
  },
  {
    question: "How does the Enterprise plan work for teams?",
    answer: "The Enterprise plan provides admin controls for managing team enrollments, creating custom learning paths aligned to your business goals, tracking individual and team progress through detailed analytics, and issuing internal certifications. Dedicated onboarding and account management is included.",
  },
  {
    question: "Is there a free trial for the Pro plan?",
    answer: "Yes! We offer a 14-day free trial for the Pro plan with full access to all features, no credit card required. You can also start with our Free plan permanently and upgrade when you're ready for advanced features.",
  },
  {
    question: "How do the hackathons and coding competitions work?",
    answer: "VedTechno hosts weekly coding challenges, monthly hackathons, and quarterly competitions with real prizes. Participants collaborate in teams, solve real-world problems, build projects, and gain visibility with our industry partners who often recruit top performers.",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    title: "The Future of AI in Education: How Machine Learning is Transforming Learning",
    excerpt: "Explore how artificial intelligence is revolutionizing personalized education and creating adaptive learning experiences that respond to individual needs.",
    content: "Full content here...",
    author: "Dr. Sarah Chen",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&h=50&fit=crop&crop=face",
    category: "AI & Education",
    tags: ["AI", "Machine Learning", "EdTech", "Future"],
    publishedAt: "2026-05-28",
    readTime: "8 min read",
    thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=400&fit=crop",
    views: 12450,
    likes: 892,
  },
  {
    id: "2",
    title: "10 Essential Skills Every Full Stack Developer Needs in 2026",
    excerpt: "The tech landscape is evolving fast. Here's what full stack developers must master to stay competitive in today's market.",
    content: "Full content here...",
    author: "Alex Johnson",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=50&h=50&fit=crop&crop=face",
    category: "Career Development",
    tags: ["Full Stack", "Career", "Web Development", "Skills"],
    publishedAt: "2026-05-20",
    readTime: "6 min read",
    thumbnail: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&h=400&fit=crop",
    views: 9870,
    likes: 743,
  },
  {
    id: "3",
    title: "Building Your First Machine Learning Model: A Beginner's Guide",
    excerpt: "Step-by-step walkthrough of creating a real ML model from data collection to deployment, perfect for beginners.",
    content: "Full content here...",
    author: "Dr. Raj Patel",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=50&h=50&fit=crop&crop=face",
    category: "Machine Learning",
    tags: ["Python", "ML", "Tutorial", "Beginner"],
    publishedAt: "2026-05-15",
    readTime: "12 min read",
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=600&h=400&fit=crop",
    views: 7650,
    likes: 621,
  },
  {
    id: "4",
    title: "Cloud Security Best Practices: Protecting Your Infrastructure in 2026",
    excerpt: "A comprehensive guide to securing cloud environments, from IAM policies to encryption and compliance frameworks.",
    content: "Full content here...",
    author: "Emma Wilson",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=50&h=50&fit=crop&crop=face",
    category: "Cybersecurity",
    tags: ["Cloud", "Security", "AWS", "DevSecOps"],
    publishedAt: "2026-05-10",
    readTime: "10 min read",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&h=400&fit=crop",
    views: 6230,
    likes: 498,
  },
  {
    id: "5",
    title: "From Student to Senior Developer: A 2-Year Journey with VedTechno",
    excerpt: "Real story of how structured learning, projects, and community helped one student land a $120K developer role.",
    content: "Full content here...",
    author: "Marcus Chen",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50&h=50&fit=crop&crop=face",
    category: "Success Stories",
    tags: ["Career", "Success", "Journey", "Inspiration"],
    publishedAt: "2026-05-05",
    readTime: "7 min read",
    thumbnail: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop",
    views: 15670,
    likes: 1234,
  },
  {
    id: "6",
    title: "Kubernetes vs Docker Swarm: Which Orchestration Tool Should You Learn?",
    excerpt: "A technical comparison of the two dominant container orchestration platforms to help you make the right learning investment.",
    content: "Full content here...",
    author: "Michael Torres",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=50&h=50&fit=crop&crop=face",
    category: "Cloud & DevOps",
    tags: ["Kubernetes", "Docker", "DevOps", "Cloud"],
    publishedAt: "2026-04-28",
    readTime: "9 min read",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=400&fit=crop",
    views: 8910,
    likes: 712,
  },
];

export const STATS = [
  { label: "Active Learners", value: 250000, suffix: "+" },
  { label: "Courses Available", value: 1200, suffix: "+" },
  { label: "Certifications Issued", value: 85000, suffix: "+" },
  { label: "Hiring Partners", value: 500, suffix: "+" },
];

export const NAV_LINKS = [
  { label: "Features", href: "/features" },
  { label: "Pricing", href: "/pricing" },
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" },
];

export const FOOTER_LINKS = {
  Product: [
    { label: "Features", href: "/features" },
    { label: "Pricing", href: "/pricing" },
    { label: "Dashboard", href: "/dashboard" },
    { label: "Changelog", href: "/blog" },
  ],
  Company: [
    { label: "About Us", href: "/about" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "/contact" },
    { label: "Careers", href: "/about" },
  ],
  Resources: [
    { label: "Documentation", href: "/features" },
    { label: "Community", href: "/dashboard" },
    { label: "FAQ", href: "/faq" },
    { label: "Tutorials", href: "/blog" },
  ],
  Legal: [
    { label: "Privacy Policy", href: "/privacy" },
    { label: "Terms of Service", href: "/terms" },
    { label: "Cookie Policy", href: "/privacy" },
    { label: "Security", href: "/about" },
  ],
};

export const LEARNING_PATHS = [
  {
    icon: "💻",
    title: "Full Stack Development",
    courses: 24,
    duration: "6 months",
    skills: ["React", "Node.js", "Database", "DevOps"],
    color: "from-blue-500 to-indigo-600",
  },
  {
    icon: "🤖",
    title: "AI & Machine Learning",
    courses: 18,
    duration: "5 months",
    skills: ["Python", "TensorFlow", "NLP", "Computer Vision"],
    color: "from-emerald-500 to-teal-600",
  },
  {
    icon: "☁️",
    title: "Cloud Engineering",
    courses: 16,
    duration: "4 months",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform"],
    color: "from-violet-500 to-purple-600",
  },
  {
    icon: "🔒",
    title: "Cybersecurity",
    courses: 14,
    duration: "4 months",
    skills: ["Networking", "Ethical Hacking", "SIEM", "Compliance"],
    color: "from-orange-500 to-red-600",
  },
];
