import type { Course, Testimonial, PricingPlan, FAQ, BlogPost } from "@/types";

export const MOCK_COURSES: Course[] = [
  {
    id: "1",
    title: "Full Stack Web Development Bootcamp",
    description: "Master React, Node.js, MongoDB, and deploy production apps.",
    instructor: "Alex Johnson",
    category: "Web Development",
    level: "Intermediate",
    duration: "48 hours",
    students: 12450,
    rating: 4.9,
    reviews: 2341,
    price: 79,
    originalPrice: 199,
    thumbnail: "https://images.unsplash.com/photo-1627398242454-45a1465c2479?w=400&h=250&fit=crop",
    tags: ["React", "Node.js", "MongoDB", "TypeScript"],
    progress: 65,
  },
  {
    id: "2",
    title: "Machine Learning with Python",
    description: "Build real ML models from regression to neural networks.",
    instructor: "Dr. Sarah Chen",
    category: "AI & ML",
    level: "Advanced",
    duration: "56 hours",
    students: 8920,
    rating: 4.8,
    reviews: 1876,
    price: 89,
    originalPrice: 249,
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=400&h=250&fit=crop",
    tags: ["Python", "TensorFlow", "Scikit-learn", "Deep Learning"],
    progress: 30,
  },
  {
    id: "3",
    title: "Cloud Architecture on AWS",
    description: "Design, deploy, and manage scalable cloud infrastructure.",
    instructor: "Michael Torres",
    category: "Cloud Computing",
    level: "Intermediate",
    duration: "40 hours",
    students: 6780,
    rating: 4.7,
    reviews: 1234,
    price: 69,
    originalPrice: 189,
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&h=250&fit=crop",
    tags: ["AWS", "Docker", "Kubernetes", "DevOps"],
  },
  {
    id: "4",
    title: "Cybersecurity Fundamentals",
    description: "Learn ethical hacking, network security, and threat analysis.",
    instructor: "Emma Wilson",
    category: "Cybersecurity",
    level: "Beginner",
    duration: "32 hours",
    students: 9450,
    rating: 4.8,
    reviews: 1987,
    price: 59,
    originalPrice: 149,
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=400&h=250&fit=crop",
    tags: ["Security", "Networking", "Ethical Hacking", "OWASP"],
  },
  {
    id: "5",
    title: "Data Science & Analytics",
    description: "Transform raw data into actionable business insights.",
    instructor: "Dr. Raj Patel",
    category: "Data Science",
    level: "Intermediate",
    duration: "44 hours",
    students: 7650,
    rating: 4.9,
    reviews: 1654,
    price: 75,
    originalPrice: 199,
    thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=400&h=250&fit=crop",
    tags: ["Python", "SQL", "Tableau", "Statistics"],
  },
  {
    id: "6",
    title: "Mobile App Development with React Native",
    description: "Build cross-platform iOS and Android apps with one codebase.",
    instructor: "Lisa Park",
    category: "Mobile Development",
    level: "Intermediate",
    duration: "38 hours",
    students: 5430,
    rating: 4.7,
    reviews: 987,
    price: 65,
    originalPrice: 169,
    thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400&h=250&fit=crop",
    tags: ["React Native", "iOS", "Android", "Expo"],
    isFree: false,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "1",
    name: "Priya Sharma",
    role: "Frontend Developer",
    company: "TechCorp India",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
    content: "VedTechno transformed my career. The AI coding assistant helped me understand complex concepts faster than any bootcamp I've attended. Got hired within 3 months!",
    rating: 5,
  },
  {
    id: "2",
    name: "Marcus Chen",
    role: "Data Scientist",
    company: "DataWave Analytics",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    content: "The project-based learning approach is exceptional. I built 5 real-world projects that became the backbone of my portfolio. The AI guidance was invaluable.",
    rating: 5,
  },
  {
    id: "3",
    name: "Sarah Mitchell",
    role: "Cloud Engineer",
    company: "CloudNine Solutions",
    avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    content: "I earned my AWS certification through VedTechno in just 2 months. The practice environments are top-notch and the community support is incredible.",
    rating: 5,
  },
  {
    id: "4",
    name: "Arjun Nair",
    role: "Startup Founder",
    company: "NeuralStack",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    content: "The Innovation Hub gave my startup the technical foundation it needed. Mentorship access and the founder community helped us launch our product 40% faster.",
    rating: 5,
  },
  {
    id: "5",
    name: "Emily Rodriguez",
    role: "HR & L&D Manager",
    company: "Global Enterprises",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop&crop=face",
    content: "We enrolled 150 employees on the enterprise plan. The team analytics helped us identify skill gaps and improve our tech capabilities by 60% in one quarter.",
    rating: 5,
  },
  {
    id: "6",
    name: "David Kim",
    role: "Full Stack Developer",
    company: "Freelance",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    content: "The interactive coding lab with multi-language support is phenomenal. I can switch between Python, JavaScript, and Go seamlessly. Best learning investment I've made.",
    rating: 5,
  },
];

export const PRICING_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    description: "Perfect for beginners exploring technology learning.",
    price: { monthly: 0, annual: 0 },
    features: [
      "5 free courses access",
      "Basic coding challenges",
      "Community forum access",
      "1 project lab",
      "Email support",
      "Basic skill assessments",
    ],
  },
  {
    id: "pro",
    name: "Pro",
    description: "For serious learners and professionals.",
    price: { monthly: 29, annual: 19 },
    features: [
      "Unlimited course access",
      "AI coding assistant",
      "Advanced coding labs",
      "10 project labs",
      "Digital certificates",
      "Career roadmaps",
      "Mock interviews",
      "Priority support",
      "Resume builder",
      "Job board access",
    ],
    highlighted: true,
    badge: "Most Popular",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    description: "For teams and organizations scaling their tech talent.",
    price: { monthly: 99, annual: 79 },
    features: [
      "Everything in Pro",
      "Team management",
      "Custom learning paths",
      "Advanced analytics",
      "Employee certifications",
      "Corporate training programs",
      "Dedicated account manager",
      "SSO & SAML support",
      "API access",
      "Custom branding",
    ],
  },
];

export const FAQS: FAQ[] = [
  {
    question: "What makes VedTechno different from other online learning platforms?",
    answer: "VedTechno combines AI-powered learning tools, interactive coding labs, real-world project building, and career development in one ecosystem. Our AI coding assistant provides personalized guidance, while our project-based approach ensures you build a portfolio that stands out to employers.",
  },
  {
    question: "How does the AI Coding Assistant work?",
    answer: "Our AI Coding Assistant analyzes your code in real-time, provides intelligent suggestions, detects bugs, offers refactoring recommendations, and generates documentation. It learns from your coding patterns to provide increasingly personalized guidance as you progress.",
  },
  {
    question: "Are the certifications industry-recognized?",
    answer: "Yes! VedTechno certifications are recognized by hundreds of tech companies worldwide. Our assessments are proctored, skill-validated, and include digital badges verifiable on LinkedIn and professional platforms. Many of our employer partners specifically seek VedTechno certified candidates.",
  },
  {
    question: "Can I access courses on mobile devices?",
    answer: "Absolutely! VedTechno is fully responsive and optimized for mobile learning. Our mobile app (iOS & Android) lets you continue lessons, participate in discussions, and even code directly from your phone with our mobile-optimized code editor.",
  },
  {
    question: "What programming languages does the coding lab support?",
    answer: "Our Interactive Coding Lab supports 20+ programming languages including Python, JavaScript, TypeScript, Java, C++, Go, Rust, PHP, Ruby, Swift, Kotlin, and more. Multi-language projects with cross-language support are also available for full-stack development.",
  },
  {
    question: "How does the Enterprise plan work for teams?",
    answer: "The Enterprise plan provides admin controls for managing team enrollments, creating custom learning paths aligned to your business goals, tracking individual and team progress through detailed analytics, and issuing internal certifications. Dedicated onboarding and account management is included.",
  },
  {
    question: "Is there a free trial for the Pro plan?",
    answer: "Yes! We offer a 14-day free trial for the Pro plan with full access to all features, no credit card required. You can also start with our Free plan permanently and upgrade when you're ready for advanced features.",
  },
  {
    question: "How do the hackathons and coding competitions work?",
    answer: "VedTechno hosts weekly coding challenges, monthly hackathons, and quarterly competitions with real prizes. Participants collaborate in teams, solve real-world problems, build projects, and gain visibility with our industry partners who often recruit top performers.",
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: "1",
    title: "The Future of AI in Education: How Machine Learning is Transforming Learning",
    excerpt: "Explore how artificial intelligence is revolutionizing personalized education and creating adaptive learning experiences that respond to individual needs.",
    content: `<p>Artificial Intelligence is no longer just a futuristic concept; it is actively transforming the landscape of education. Traditionally, classroom learning followed a one-size-fits-all model. However, machine learning algorithms are now making it possible to tailor education to the unique speed, learning style, and interest of every individual student.</p><h3>1. Adaptive Learning Systems</h3><p>Adaptive learning platforms analyze a student's performance in real time and modify the curriculum accordingly. If a student struggles with a specific algebra concept, the system provides supplementary exercises and tutorials instead of pushing them to the next chapter. This ensures that foundation concepts are fully mastered.</p><h3>2. Automated Grading and Feedback</h3><p>Teachers spend dozens of hours grading papers and homework. Modern AI tools can automate the grading of standardized tests, coding assignments, and even essays. By giving instantaneous, detailed feedback, students can learn from mistakes immediately, while educators can focus on personal tutoring.</p><h3>3. Intelligent Tutoring Systems</h3><p>AI assistants function as 24/7 tutors. They can answer students' questions, explain complex physics simulations, or guide code debugs at 2 AM. This levels the playing field for students who cannot afford private tutors.</p>`,
    author: "Dr. Sarah Chen",
    authorAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&h=50&fit=crop&crop=face",
    category: "AI & Education",
    tags: ["AI", "Machine Learning", "EdTech", "Future"],
    publishedAt: "2026-05-28",
    readTime: "8 min read",
    thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=600&h=400&fit=crop",
    views: 12450,
    likes: 892,
  },
  {
    id: "2",
    title: "10 Essential Skills Every Full Stack Developer Needs in 2026",
    excerpt: "The tech landscape is evolving fast. Here's what full stack developers must master to stay competitive in today's market.",
    content: `<p>The tech landscape moves at a breakneck pace. As we head further into 2026, the expectations from full stack developers have shifted significantly from just writing basic CRUD applications to building intelligent, performant, and secure systems. Here are the top 10 skills you need:</p><ul><li><strong>1. Advanced TypeScript:</strong> Strong type safety, generics, and template literal types are standard.</li><li><strong>2. AI Assisted Coding:</strong> Leveraging tools like Copilot, Gemini, and custom agents efficiently.</li><li><strong>3. Next-Gen Frameworks:</strong> Deep knowledge of server components, React Server Actions, or SolidJS/SvelteKit.</li><li><strong>4. Edge Computing:</strong> Deploying APIs on cloudflare workers, Vercel edge, or Supabase edge functions.</li><li><strong>5. AI Integration:</strong> Integrating LLM APIs, prompt engineering, and managing vector databases (Pinecone, pgvector).</li><li><strong>6. Zero-Trust Security:</strong> Implementing OAuth2, MFA, and absolute data encryption at rest and in transit.</li><li><strong>7. Containerization and Orchestration:</strong> Basic Docker, Kubernetes, and automated CI/CD pipelines.</li><li><strong>8. Performance Optimization:</strong> Core Web Vitals, SSR, streaming rendering, and asset caching strategies.</li><li><strong>9. Real-Time Architecture:</strong> WebSockets, WebRTC, and SSE for collaborative applications.</li><li><strong>10. Soft Skills:</strong> Clear communication, collaboration, and high adaptability.</li></ul>`,
    author: "Alex Johnson",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=50&h=50&fit=crop&crop=face",
    category: "Career Development",
    tags: ["Full Stack", "Career", "Web Development", "Skills"],
    publishedAt: "2026-05-20",
    readTime: "6 min read",
    thumbnail: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=600&h=400&fit=crop",
    views: 9870,
    likes: 743,
  },
  {
    id: "3",
    title: "Building Your First Machine Learning Model: A Beginner's Guide",
    excerpt: "Step-by-step walkthrough of creating a real ML model from data collection to deployment, perfect for beginners.",
    content: `<p>Starting with machine learning can seem daunting. However, building your first model is actually quite straightforward if you follow a step-by-step process. In this guide, we'll walk through building a simple regression model using Python and Scikit-learn.</p><h3>Step 1: Define the Problem</h3><p>Before writing code, understand what you want to predict. For this tutorial, we will predict house prices based on features like square footage, number of bedrooms, and location.</p><h3>Step 2: Collect and Prepare Data</h3><p>Clean data is the foundation of good machine learning. Use Pandas to load your CSV, handle missing values, and scale numerical values so the model can process them accurately.</p><h3>Step 3: Split the Dataset</h3><p>Split your data into a training set (usually 80%) and a test set (20%) using Scikit-learn's <code>train_test_split</code> helper function. This prevents overfitting.</p><h3>Step 4: Train and Evaluate</h3><p>Instantiate a Linear Regression model, fit it to the training data, and evaluate its performance on the test set using Mean Squared Error (MSE).</p>`,
    author: "Dr. Raj Patel",
    authorAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=50&h=50&fit=crop&crop=face",
    category: "Machine Learning",
    tags: ["Python", "ML", "Tutorial", "Beginner"],
    publishedAt: "2026-05-15",
    readTime: "12 min read",
    thumbnail: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=600&h=400&fit=crop",
    views: 7650,
    likes: 621,
  },
  {
    id: "4",
    title: "Cloud Security Best Practices: Protecting Your Infrastructure in 2026",
    excerpt: "A comprehensive guide to securing cloud environments, from IAM policies to encryption and compliance frameworks.",
    content: `<p>With more organizations migrating their critical assets to public clouds, maintaining a robust security posture is of paramount importance. Below are the best practices you must enforce to keep your cloud infrastructure secure:</p><h3>1. Enforce Principle of Least Privilege (PoLP)</h3><p>Never grant full admin access by default. Use IAM roles, policy boundaries, and temporary credentials. Ensure that services and users have access to only the resources they explicitly require.</p><h3>2. Multi-Factor Authentication (MFA)</h3><p>Require MFA for all console logins, especially for root accounts. Use hardware security keys or authenticator apps rather than SMS-based verification.</p><h3>3. Implement End-to-End Encryption</h3><p>Encrypt sensitive data both at rest (using KMS keys) and in transit (using TLS 1.3). Never allow unencrypted HTTP traffic to touch your database or app servers.</p><h3>4. Automated Audits & Vulnerability Scanning</h3><p>Set up continuous threat detection tools (such as AWS GuardDuty) and regular vulnerability scanning in your CI/CD pipeline to catch security issues before deployment.</p>`,
    author: "Emma Wilson",
    authorAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=50&h=50&fit=crop&crop=face",
    category: "Cybersecurity",
    tags: ["Cloud", "Security", "AWS", "DevSecOps"],
    publishedAt: "2026-05-10",
    readTime: "10 min read",
    thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&h=400&fit=crop",
    views: 6230,
    likes: 498,
  },
  {
    id: "5",
    title: "From Student to Senior Developer: A 2-Year Journey with VedTechno",
    excerpt: "Real story of how structured learning, projects, and community helped one student land a $120K developer role.",
    content: `<p>Two years ago, Marcus was a first-year college student wondering how to break into the tech industry. Today, he is a Senior Full Stack Engineer at a fast-growing startup. Here's how he did it with the help of VedTechno:</p><blockquote>"When I started, I knew basic HTML and CSS. I felt completely lost looking at complex repositories. The structured career paths on VedTechno gave me a roadmap, and the interactive coding lab allowed me to experiment without breaking things locally."</blockquote><h3>Real Projects Over Tutorials</h3><p>Instead of falling into tutorial hell, Marcus focused on project-based learning. He built a real-time chat application, a serverless API, and a containerized task scheduler. These became the foundation of his portfolio, showing employers he had practical knowledge.</p><h3>Mentorship and Mock Interviews</h3><p>Through VedTechno's premium career tools, Marcus engaged in mock interviews and code reviews. The detailed feedback allowed him to refine his system design explanations, ultimately leading to a successful interview cycle.</p>`,
    author: "Marcus Chen",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=50&h=50&fit=crop&crop=face",
    category: "Success Stories",
    tags: ["Career", "Success", "Journey", "Inspiration"],
    publishedAt: "2026-05-05",
    readTime: "7 min read",
    thumbnail: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=600&h=400&fit=crop",
    views: 15670,
    likes: 1234,
  },
  {
    id: "6",
    title: "Kubernetes vs Docker Swarm: Which Orchestration Tool Should You Learn?",
    excerpt: "A technical comparison of the two dominant container orchestration platforms to help you make the right learning investment.",
    content: `<p>If you're diving into container orchestration, you've probably encountered Kubernetes and Docker Swarm. Both serve the same fundamental purpose: managing containerized applications across multiple servers. However, they target different use cases and skill levels.</p><h3>Docker Swarm: Simplicity First</h3><p>Docker Swarm is built directly into Docker. It is exceptionally easy to configure and ideal for small to medium setups where speed and minimal complexity are the priorities. You write a standard Docker Compose file and deploy it to a cluster in seconds.</p><h3>Kubernetes: Scale and Flexibility</h3><p>Kubernetes (K8s) is the industry standard for enterprise deployments. It handles auto-scaling, self-healing, rolling updates, and complex ingress routing. The learning curve is steep, but it offers unparalleled power and customizability for high-traffic environments.</p><h3>Which Should You Learn?</h3><p>If you are just starting with containers, learn Docker Swarm first to understand clustering principles. However, if you are looking for enterprise jobs, learning Kubernetes is essential.</p>`,
    author: "Michael Torres",
    authorAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=50&h=50&fit=crop&crop=face",
    category: "Cloud & DevOps",
    tags: ["Kubernetes", "Docker", "DevOps", "Cloud"],
    publishedAt: "2026-04-28",
    readTime: "9 min read",
    thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&h=400&fit=crop",
    views: 8910,
    likes: 712,
  },
];

export const STATS = [
  { label: "Active Learners", value: 250000, suffix: "+" },
  { label: "Courses Available", value: 1200, suffix: "+" },
  { label: "Certifications Issued", value: 85000, suffix: "+" },
  { label: "Hiring Partners", value: 500, suffix: "+" },
];

export const NAV_LINKS = [
  { label: "Features", href: "/features" },
  { label: "Projects", href: "/projects" },
  { label: "Pricing", href: "/pricing" },
  { label: "Blog", href: "/blog" },
  { label: "About", href: "/about" },
];

export const FOOTER_LINKS = {
  Product: [
    { label: "Features", href: "/features" },
    { label: "Pricing", href: "/pricing" },
    { label: "Dashboard", href: "/dashboard" },
    { label: "Changelog", href: "/changelog" },
  ],
  Company: [
    { label: "About Us", href: "/about" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "/contact" },
    { label: "Careers", href: "/careers" },
  ],
  Resources: [
    { label: "Documentation", href: "/docs" },
    { label: "Community", href: "/community" },
    { label: "FAQ", href: "/faq" },
    { label: "Tutorials", href: "/tutorials" },
  ],
  Legal: [
    { label: "Privacy Policy", href: "/privacy" },
    { label: "Terms of Service", href: "/terms" },
    { label: "Cookie Policy", href: "/cookies" },
    { label: "Security", href: "/security" },
  ],
};

export const LEARNING_PATHS = [
  {
    icon: "💻",
    title: "Full Stack Development",
    courses: 24,
    duration: "6 months",
    skills: ["React", "Node.js", "Database", "DevOps"],
    color: "from-blue-500 to-indigo-600",
  },
  {
    icon: "🤖",
    title: "AI & Machine Learning",
    courses: 18,
    duration: "5 months",
    skills: ["Python", "TensorFlow", "NLP", "Computer Vision"],
    color: "from-emerald-500 to-teal-600",
  },
  {
    icon: "☁️",
    title: "Cloud Engineering",
    courses: 16,
    duration: "4 months",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform"],
    color: "from-violet-500 to-purple-600",
  },
  {
    icon: "🔒",
    title: "Cybersecurity",
    courses: 14,
    duration: "4 months",
    skills: ["Networking", "Ethical Hacking", "SIEM", "Compliance"],
    color: "from-orange-500 to-red-600",
  },
];
